<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\SiteSetting;
use App\Models\SubscriptionPayment;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserController extends Controller
{
    /**
     * Display a listing of registered candidates, subscribers, and admins.
     */
    public function index(Request $request)
    {
        $query = User::query();

        // Search by keyword: Name, Email, or 10-digit Phone
        if ($request->filled('q')) {
            $search = trim($request->input('q'));
            $cleanPhone = preg_replace('/\D/', '', $search);

            $query->where(function ($q) use ($search, $cleanPhone) {
                $q->where('name', 'like', "%{$search}%")
                  ->orWhere('email', 'like', "%{$search}%");

                if (!empty($cleanPhone)) {
                    $q->orWhere('phone', 'like', "%{$cleanPhone}%");
                }
            });
        }

        // Status Filter
        $filter = $request->input('status', 'all');
        if ($filter === 'pro') {
            $query->where('subscribed_until', '>', now());
        } elseif ($filter === 'free') {
            $query->where(function ($q) {
                $q->whereNull('subscribed_until')
                  ->orWhere('subscribed_until', '<=', now());
            })->where('is_admin', false)
              ->where('email', '!=', 'admin@pscranker.com')
              ->where('phone', '!=', '9895940500');
        } elseif ($filter === 'admin') {
            $query->where(function ($q) {
                $q->where('is_admin', true)
                  ->orWhere('email', 'admin@pscranker.com')
                  ->orWhere('phone', '9895940500');
            });
        }

        // Summary Counts
        $totalUsers = User::count();
        $totalPro = User::where('subscribed_until', '>', now())->count();
        $totalFree = User::where(function ($q) {
            $q->whereNull('subscribed_until')
              ->orWhere('subscribed_until', '<=', now());
        })->count();
        $totalAdmins = User::where('is_admin', true)
            ->orWhere('email', 'admin@pscranker.com')
            ->orWhere('phone', '9895940500')
            ->count();

        $users = $query->latest('id')->paginate(20)->withQueryString();

        $pricingTiers = SiteSetting::getPricingTiers();

        return view('admin.users.index', compact(
            'users',
            'totalUsers',
            'totalPro',
            'totalFree',
            'totalAdmins',
            'filter',
            'pricingTiers'
        ));
    }

    /**
     * Store a newly created candidate account manually (with optional offline subscription & admin role).
     */
    public function store(Request $request)
    {
        // Sanitize phone number to digits only
        if ($request->filled('phone')) {
            $request->merge([
                'phone' => preg_replace('/\D/', '', $request->input('phone')),
            ]);
        }

        $validated = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'phone' => ['required', 'string', 'regex:/^[0-9]{10}$/', 'unique:users,phone'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email'],
            'password' => ['nullable', 'string', 'min:6'],
            'is_admin' => ['nullable', 'boolean'],
            'activate_subscription' => ['nullable', 'boolean'],
            'duration_months' => ['nullable', 'integer', 'min:1'],
            'payment_mode' => ['nullable', 'string', 'in:cash,gpay_upi,bank_transfer,gift,scholarship,other'],
            'amount' => ['nullable', 'numeric', 'min:0'],
            'notes' => ['nullable', 'string', 'max:500'],
        ], [
            'phone.regex' => 'The mobile number must be exactly 10 digits.',
            'phone.unique' => 'This mobile number is already registered in the system.',
            'email.unique' => 'This email address is already registered in the system.',
        ]);

        // Auto-generate password if not provided
        $autoGeneratedPassword = false;
        $plainPassword = $request->filled('password') ? $request->input('password') : null;
        if (!$plainPassword) {
            $autoGeneratedPassword = true;
            $plainPassword = 'Psc@' . mt_rand(1000, 9999);
        }

        $isAdmin = $request->boolean('is_admin');

        $user = User::create([
            'name' => trim($validated['name']),
            'phone' => $validated['phone'],
            'email' => strtolower(trim($validated['email'])),
            'password' => Hash::make($plainPassword),
            'is_admin' => $isAdmin,
        ]);

        // If subscription is requested upon account creation
        $subscriptionGranted = false;
        if ($request->boolean('activate_subscription')) {
            $durationMonths = (int) ($request->input('duration_months') ?? 1);
            $paymentMode = $request->input('payment_mode', 'cash');
            $amount = $request->filled('amount') ? (float) $request->input('amount') : 0.00;
            $notes = $request->input('notes', '');

            // Duration: if 120, treat as lifetime
            $newExpiry = $durationMonths >= 120
                ? now()->addYears(10)
                : now()->addMonths($durationMonths);

            $orderPrefix = in_array($paymentMode, ['gift', 'scholarship']) ? 'GIFT_' : 'OFFLINE_';
            $uniqueOrderId = $orderPrefix . strtoupper(uniqid());

            SubscriptionPayment::create([
                'user_id' => $user->id,
                'razorpay_order_id' => $uniqueOrderId,
                'razorpay_payment_id' => 'OFFLINE_' . strtoupper($paymentMode) . '_' . date('YmdHis'),
                'amount' => $amount,
                'currency' => 'INR',
                'duration_months' => $durationMonths,
                'rebate_percentage' => 0,
                'status' => 'paid',
                'payment_metadata' => [
                    'source' => 'admin_account_creation',
                    'method' => $paymentMode,
                    'notes' => $notes,
                    'created_by_admin' => auth()->user()->name ?? 'Admin',
                    'created_at' => now()->toIso8601String(),
                ],
            ]);

            $user->subscribed_until = $newExpiry;
            $user->subscription_plan = $durationMonths >= 120 ? 'PRO Lifetime Pass' : "PRO ({$durationMonths} Months - Offline)";
            $user->subscription_amount = $amount;
            $user->save();

            $subscriptionGranted = true;
        }

        $statusMsg = "Account for {$user->name} ({$user->phone}) created successfully!";
        if ($autoGeneratedPassword) {
            $statusMsg .= " Assigned Password: {$plainPassword}";
        }
        if ($subscriptionGranted) {
            $statusMsg .= " PRO subscription activated until " . $user->subscribed_until->format('d M Y') . ".";
        }
        if ($isAdmin) {
            $statusMsg .= " Admin privileges granted.";
        }

        return redirect()->back()
            ->with('success', $statusMsg)
            ->with('new_user_credentials', [
                'name' => $user->name,
                'phone' => $user->phone,
                'email' => $user->email,
                'password' => $plainPassword,
            ]);
    }

    /**
     * Gift or activate an offline PRO subscription for an existing candidate.
     */
    public function giftSubscription(Request $request, User $user)
    {
        $validated = $request->validate([
            'duration_months' => ['required', 'integer', 'min:1'],
            'payment_mode' => ['required', 'string', 'in:cash,gpay_upi,bank_transfer,gift,scholarship,other'],
            'amount' => ['nullable', 'numeric', 'min:0'],
            'notes' => ['nullable', 'string', 'max:500'],
        ]);

        $durationMonths = (int) $validated['duration_months'];
        $paymentMode = $validated['payment_mode'];
        $amount = $request->filled('amount') ? (float) $validated['amount'] : 0.00;
        $notes = $validated['notes'] ?? '';

        // Calculate new expiration date (extend if already active)
        if ($durationMonths >= 120) {
            // Lifetime
            $newExpiry = now()->addYears(10);
            $planTitle = 'PRO Lifetime Pass';
        } else {
            $baseDate = ($user->subscribed_until && $user->subscribed_until->isFuture())
                ? $user->subscribed_until->copy()
                : now();

            $newExpiry = $baseDate->addMonths($durationMonths);
            $modeLabel = in_array($paymentMode, ['gift', 'scholarship']) ? 'Gift' : 'Offline';
            $planTitle = "PRO ({$durationMonths} Months - {$modeLabel})";
        }

        $orderPrefix = in_array($paymentMode, ['gift', 'scholarship']) ? 'GIFT_' : 'OFFLINE_';
        $uniqueOrderId = $orderPrefix . strtoupper(uniqid());

        SubscriptionPayment::create([
            'user_id' => $user->id,
            'razorpay_order_id' => $uniqueOrderId,
            'razorpay_payment_id' => 'OFFLINE_' . strtoupper($paymentMode) . '_' . date('YmdHis'),
            'amount' => $amount,
            'currency' => 'INR',
            'duration_months' => $durationMonths,
            'rebate_percentage' => 0,
            'status' => 'paid',
            'payment_metadata' => [
                'source' => 'admin_gift_or_offline',
                'method' => $paymentMode,
                'notes' => $notes,
                'granted_by_admin' => auth()->user()->name ?? 'Admin',
                'granted_at' => now()->toIso8601String(),
            ],
        ]);

        $user->subscribed_until = $newExpiry;
        $user->subscription_plan = $planTitle;
        $user->subscription_amount = $amount;
        $user->save();

        $modeHuman = match($paymentMode) {
            'gift' => 'Gifted Subscription',
            'scholarship' => 'Merit Scholarship',
            'gpay_upi' => 'Offline GPay / UPI',
            'bank_transfer' => 'Offline Bank Transfer',
            'cash' => 'Offline Cash Payment',
            default => 'Offline Manual Payment',
        };

        return redirect()->back()->with(
            'success',
            "{$modeHuman} activated for {$user->name}! PRO access valid until " . $newExpiry->format('d M Y') . " (Amount recorded: ₹" . number_format($amount, 2) . ")."
        );
    }

    /**
     * Grant or revoke Admin privileges for a user.
     */
    public function toggleAdmin(Request $request, User $user)
    {
        // Guard primary superadmin accounts against demotion
        if ($user->email === 'admin@pscranker.com' || $user->phone === '9895940500') {
            return redirect()->back()->with('error', 'Primary Superadmin privileges cannot be revoked.');
        }

        // Prevent admin from accidentally locking themselves out
        if ($user->id === auth()->id() && $user->is_admin) {
            return redirect()->back()->with('error', 'You cannot revoke your own admin rights to avoid accidental lockout.');
        }

        $user->is_admin = !$user->is_admin;
        $user->save();

        $action = $user->is_admin ? 'granted' : 'revoked';

        return redirect()->back()->with(
            'success',
            "Administrator privileges have been {$action} for {$user->name} ({$user->phone})."
        );
    }
}
